//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GST_Impl.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GSTBookEntities : DbContext
    {
        public GSTBookEntities()
            : base("name=GSTBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CustomerContact> CustomerContacts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<HsnHacCode> HsnHacCodes { get; set; }
        public virtual DbSet<mst_FinancialYear> mst_FinancialYear { get; set; }
        public virtual DbSet<mst_OrgInfo> mst_OrgInfo { get; set; }
        public virtual DbSet<mst_PaymentTypes> mst_PaymentTypes { get; set; }
        public virtual DbSet<mst_PurchaseOrder> mst_PurchaseOrder { get; set; }
        public virtual DbSet<mst_Receipts> mst_Receipts { get; set; }
        public virtual DbSet<mst_SalesInvoice> mst_SalesInvoice { get; set; }
        public virtual DbSet<mst_Statuses> mst_Statuses { get; set; }
        public virtual DbSet<mst_Taxes> mst_Taxes { get; set; }
        public virtual DbSet<mst_TaxTypes> mst_TaxTypes { get; set; }
        public virtual DbSet<mst_Uom> mst_Uom { get; set; }
        public virtual DbSet<ProductsAndService> ProductsAndServices { get; set; }
        public virtual DbSet<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual DbSet<ReceiptDetail> ReceiptDetails { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<VendorContact> VendorContacts { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<SalesInvoiceItem> SalesInvoiceItems { get; set; }
    
        public virtual ObjectResult<GetPOByGuid_Result> GetPOByGuid(string guid)
        {
            var guidParameter = guid != null ?
                new ObjectParameter("Guid", guid) :
                new ObjectParameter("Guid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPOByGuid_Result>("GetPOByGuid", guidParameter);
        }
    
        public virtual ObjectResult<GetPoList_Result> GetPoList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPoList_Result>("GetPoList");
        }
    
        public virtual ObjectResult<GetTaxList_Result> GetTaxList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTaxList_Result>("GetTaxList");
        }
    
        public virtual ObjectResult<GetUoms_Result> GetUoms()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUoms_Result>("GetUoms");
        }
    }
}
