//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GST_Impl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mst_PurchaseOrder()
        {
            this.mst_PurchaseOrder1 = new HashSet<mst_PurchaseOrder>();
            this.mst_SalesInvoice = new HashSet<mst_SalesInvoice>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
        }
    
        public int PO_ID { get; set; }
        public string PO_GUID { get; set; }
        public string PONO { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string DeliveryAddress { get; set; }
        public string PurchaseOffice { get; set; }
        public Nullable<System.DateTime> ExpDeliveryDate { get; set; }
        public Nullable<System.DateTime> ActualDelDate { get; set; }
        public string BuyFromBP { get; set; }
        public string BuyFromOrder { get; set; }
        public Nullable<int> AmendNo { get; set; }
        public Nullable<System.DateTime> AmendDate { get; set; }
        public string AmendRemarks { get; set; }
        public string RefA { get; set; }
        public string RefB { get; set; }
        public string GSTN { get; set; }
        public string Buyer { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<decimal> TotalAdvance { get; set; }
        public Nullable<decimal> BalanceAdvance { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsAmmended { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mst_PurchaseOrder> mst_PurchaseOrder1 { get; set; }
        public virtual mst_PurchaseOrder mst_PurchaseOrder2 { get; set; }
        public virtual mst_Statuses mst_Statuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mst_SalesInvoice> mst_SalesInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
    }
}
