//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GST_Impl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_Receipts
    {
        public int ReceiptId { get; set; }
        public string ReceiptCode { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<int> SalesInvoiceId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<decimal> ReceiptAmt { get; set; }
        public string BilledTo { get; set; }
        public string ShippedTo { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public string PaymentRefNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual mst_PaymentTypes mst_PaymentTypes { get; set; }
        public virtual mst_SalesInvoice mst_SalesInvoice { get; set; }
    }
}
