//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GST_Impl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_SalesInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mst_SalesInvoice()
        {
            this.mst_Receipts = new HashSet<mst_Receipts>();
            this.SalesInvoiceItems = new HashSet<SalesInvoiceItem>();
        }
    
        public int InvoiceId { get; set; }
        public string GUID { get; set; }
        public string InvoiceCode { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> PoId { get; set; }
        public string BilledTo { get; set; }
        public string ShippedTo { get; set; }
        public string Client_Gstn { get; set; }
        public string Client_PAN_No { get; set; }
        public string ChallanCode { get; set; }
        public Nullable<System.DateTime> ChallanDate { get; set; }
        public string VendorCode { get; set; }
        public string E_Way_Bill_No { get; set; }
        public Nullable<int> PlaceOfSupply { get; set; }
        public string ReverseCharge { get; set; }
        public string InsurancePolicy { get; set; }
        public string PolicyNo { get; set; }
        public Nullable<System.DateTime> PolicyStartDt { get; set; }
        public Nullable<System.DateTime> PilicyEndDt { get; set; }
        public string Transport { get; set; }
        public string LR_No { get; set; }
        public Nullable<System.DateTime> LR_Dt { get; set; }
        public string VehicleNo { get; set; }
        public string IR_No { get; set; }
        public Nullable<System.DateTime> IR_Dt { get; set; }
        public Nullable<int> ReceiptId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual mst_PurchaseOrder mst_PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mst_Receipts> mst_Receipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesInvoiceItem> SalesInvoiceItems { get; set; }
    }
}
