//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GST_Impl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsAndService
    {
        public int ProductId { get; set; }
        public Nullable<int> MakeId { get; set; }
        public string Description { get; set; }
        public Nullable<int> HsnHacCodeId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual HsnHacCode HsnHacCode { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
