//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GST_Impl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrderDetail()
        {
            this.SalesInvoiceItems = new HashSet<SalesInvoiceItem>();
        }
    
        public int PoDetailId { get; set; }
        public Nullable<int> PO_ID { get; set; }
        public string ProjectCode { get; set; }
        public string WBS { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> UomId { get; set; }
        public Nullable<decimal> ItemAdvance { get; set; }
        public Nullable<decimal> BasicRate { get; set; }
        public Nullable<decimal> BasicAmt { get; set; }
        public Nullable<decimal> TotalBasic { get; set; }
        public Nullable<int> IGSTorCGST { get; set; }
        public Nullable<int> SGSTorUGST { get; set; }
        public Nullable<int> OtherTax { get; set; }
        public Nullable<decimal> IGSTorCGST_Amt { get; set; }
        public Nullable<decimal> SGSTorUGST_Amt { get; set; }
        public Nullable<decimal> OtherTax_Amt { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public Nullable<int> HsnSacCode { get; set; }
        public Nullable<System.DateTime> ItemDelDate { get; set; }
        public string ItemDescription { get; set; }
    
        public virtual HsnHacCode HsnHacCode { get; set; }
        public virtual mst_PurchaseOrder mst_PurchaseOrder { get; set; }
        public virtual mst_Taxes mst_Taxes { get; set; }
        public virtual mst_Taxes mst_Taxes1 { get; set; }
        public virtual mst_Taxes mst_Taxes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesInvoiceItem> SalesInvoiceItems { get; set; }
    }
}
